version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: library-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./backend/mongodb-init.js:/docker-entrypoint-initdb.d/mongodb-init.js:ro
    environment:
      MONGO_INITDB_DATABASE: library_management
    networks:
      - library-network

  # Backend API
  backend:
    build: ./backend
    container_name: library-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/library_management
      - JWT_SECRET=smriti_pustakalaya_college_secret_key_2024
      - PORT=5000
    volumes:
      - ./backend/logs:/app/logs
    networks:
      - library-network

  # Admin Panel
  admin-panel:
    build: ./smriti-pustakalaya
    container_name: library-admin
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - library-network

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: library-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - admin-panel
    networks:
      - library-network

volumes:
  mongodb_data:
    driver: local

networks:
  library-network:
    driver: bridge 